// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxmhdhthqaevrcfjebcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4bWhkaHRocWFldnJjZmplYmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODgzMjcsImV4cCI6MjA2NDI2NDMyN30.9HzhpiQKZOVRqzIgay3OWLlB9xytARpGgf5Cl7O8v7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);